version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
  mongodb-standalone:
    image: mongo:latest
    container_name: mongodb-standalone
#    environment:
#      -MONGO_INITDB_ROOT_USERNAME=
#      -MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 27017:27017
  springboot-docker-container:
    image: pubg-spring-boot
    container_name: pubg-spring-boot
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
